#!/bin/bash

PROG="/usr/bin/ledstrip"
COLOR="white"
HARDWARE_CONF="/var/run/hardware.conf"

test -n "${OS_VERSION}" || source /etc/init.d/base

function set_boot_leds_later() {
    while ! [[ -f ${HARDWARE_CONF} ]]; do  # Wait for hardware config to be ready
        sleep 1
    done
    
    source ${HARDWARE_CONF}
    test "${HAS_LED_STRIP}" == true || return

    ${PROG} on ${COLOR}
}


case "$1" in
    start)
        set_boot_leds_later &>/dev/null &
        ;;

    stop)
        true
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit 0  # Always exit successfully, even if LED program crashes
