#!/bin/bash

PROG_ECC_INFO="/usr/libexec/eccinfo"
PROG_CHIP_ID="/opt/packet_forwarder/bin/chip_id"
PROV_TESTS_URL="https://api.syncrob.it/provtests/"
LOG="/var/log/provision.log"
AUTH_TOKEN="3F4ECC8F2C95134BCA7281C83B879"


test -n "${OS_VERSION}" || source /etc/init.d/base


test_eth() {
    msg_begin "Testing ethernet adapter"
    
    if ! [[ -r /sys/class/net/eth0/address ]]; then
        msg_fail "no device"
    fi

    msg_done "passed"
}

test_wlan() {
    msg_begin "Testing WiFi adapter"
    
    if ! [[ -r /sys/class/net/wlan0/address ]]; then
        msg_fail "no device"
    fi

    msg_done "passed"
}

test_bt() {
    msg_begin "Testing Bluetooth adapter"
    
    if ! hciconfig hci0 &>/dev/null; then
        msg_fail "no device"
    fi

    msg_done "passed"
}

test_ecc() {
    msg_begin "Testing ECC chip"
    
    if ! [[ -e /dev/i2c-1 ]]; then
        msg_fail "no I2C device"
        return 1
    fi

    if ! ${PROG_ECC_INFO} &>/dev/null; then
        msg_fail "timeout talking to ECC chip"
        return 1
    fi

    msg_done "passed"
}

test_radio() {
    msg_begin "Testing radio board"
    
    cd $(dirname ${PROG_CHIP_ID})
    if ! ${PROG_CHIP_ID} &>/dev/null; then
        msg_fail "no board"
        return 1
    fi

    msg_done "passed"
}

start() {
    result=0
    eth_result=0
    wlan_result=0
    bt_result=0
    ecc_result=0
    radio_result=0

    if ! test_eth; then
        eth_result=1
        result=1
    fi
    if ! test_wlan; then
        wlan_result=1
        result=1
    fi
    if ! test_bt; then
        bt_result=1
        result=1
    fi
    if ! test_ecc; then
        ecc_result=1
        result=1
    fi
    if ! test_radio; then
        radio_result=1
        result=1
    fi

    payload="{
        \"rpi_sn\":\"${BOARD_SN}\",
        \"eth\":${eth_result},
        \"wlan\":${wlan_result},
        \"ble\":${bt_result},
        \"ecc\":${ecc_result},
        \"radio\":${radio_result}
    }"
    
    payload=$(echo "${payload}" | tr -d '\t\n ')

    curl -v --insecure --fail -L "${PROV_TESTS_URL}" \
         -H "Content-Type: application/json" \
         -H "Authorization: ${AUTH_TOKEN}" \
         -X POST -d "${payload}" &>> ${LOG}
    if [[ $? != 0 ]]; then
        result=1
    fi

    if [[ ${result} != 0 ]]; then
        reboot
    fi
    
    return ${result}
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
