#!/bin/bash

PROG_ECC_INFO="/usr/libexec/eccinfo"
PROG_CHIP_ID="/opt/packet_forwarder/bin/chip_id"
PROG_TUNNEL="/sbin/sshtunnel"
PROV_TESTS_URL="https://api.syncrob.it/provtests/"
LOG="/var/log/provision.log"
AUTH_TOKEN="3F4ECC8F2C95134BCA7281C83B879"

LED_COLOR_OK="green"
LED_COLOR_OK_PENDING="yellow"
LED_COLOR_ERROR="red"

test -n "${OS_VERSION}" || source /etc/init.d/base

source /etc/init.d/ledpattern

source /var/run/hardware.conf


test_eth() {
    msg_begin "Testing ethernet adapter"
    
    if ! [[ -r /sys/class/net/eth0/address ]]; then
        msg_fail "no device"
    fi

    msg_done "passed"
}

test_wlan() {
    msg_begin "Testing WiFi adapter"
    
    if ! [[ -r /sys/class/net/wlan0/address ]]; then
        set_led_pattern 1 ${LED_COLOR_ERROR}
        msg_fail "no device"
    fi

    set_led_pattern 1 ${LED_COLOR_OK}
    msg_done "passed"
}

test_bt() {
    msg_begin "Testing Bluetooth adapter"
    
    bt_devices=$(bluetoothctl list)
    if [[ -z "${bt_devices}" ]]; then
        set_led_pattern 2 ${LED_COLOR_ERROR}
        msg_fail "no device"
        return 1
    fi

    set_led_pattern 2 ${LED_COLOR_OK}
    msg_done "passed"
}

test_ecc() {
    msg_begin "Testing ECC chip"
    
    if ! [[ -e /dev/i2c-${I2C_BUS} ]]; then
        set_led_pattern 3 ${LED_COLOR_ERROR}
        msg_fail "no I2C bus"
        return 1
    fi

    if ! ${PROG_ECC_INFO} &>/dev/null; then
        set_led_pattern 3 ${LED_COLOR_ERROR}
        msg_fail "timeout talking to ECC chip"
        return 1
    fi

    set_led_pattern 3 ${LED_COLOR_OK_PENDING}
    msg_done "passed"
}

test_radio() {
    msg_begin "Testing radio board"
    
    cd $(dirname ${PROG_CHIP_ID})
    if ! ${PROG_CHIP_ID} -d ${SPI_DEV} &>/dev/null; then
        set_led_pattern 4 ${LED_COLOR_ERROR}
        msg_fail "no board"
        return 1
    fi

    set_led_pattern 4 ${LED_COLOR_OK}
    msg_done "passed"
}

start() {
    result=0
    eth_result=0
    wlan_result=0
    bt_result=0
    ecc_result=0
    radio_result=0

    if ! test_eth; then
        eth_result=1
        result=1
    fi
    if ! test_wlan; then
        wlan_result=1
        result=1
    fi
    if ! test_bt; then
        bt_result=1
        result=1
    fi
    if ! test_ecc; then
        ecc_result=1
        result=1
    fi
    if ! test_radio; then
        radio_result=1
        result=1
    fi

    payload="{
        \"rpi_sn\":\"${BOARD_SN}\",
        \"eth\":${eth_result},
        \"wlan\":${wlan_result},
        \"ble\":${bt_result},
        \"ecc\":${ecc_result},
        \"radio\":${radio_result}
    }"
    
    payload=$(echo "${payload}" | tr -d '\t\n ')

    curl --verbose --insecure --fail --location-trusted "${PROV_TESTS_URL}" \
         -H "Content-Type: application/json" \
         -H "Authorization: ${AUTH_TOKEN}" \
         -X POST -d "${payload}" &>> ${LOG}
    if [[ $? != 0 ]]; then
        set_led_pattern 5 ${LED_COLOR_ERROR}
        result=1
    else
        set_led_pattern 5 ${LED_COLOR_OK_PENDING}
    fi

    if [[ ${result} != 0 ]]; then
        ${PROG_TUNNEL} start
        sleep 86400
        reboot
    fi
    
    return ${result}
}

case "$1" in
    start)
        start
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
