#!/bin/bash

PROG="/sbin/fwupdate"
BASE_URL="https://fwd.syncrob.it"
FINAL_FIRMWARE_PATH="/final_firmware.img.xz"

source /final_os_info

LATEST_URL="${BASE_URL}/${FINAL_OS_PREFIX}/latest_stable_info.json"

test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
    msg_begin "Upgrading to production firmware"
    
    if [[ -s ${FINAL_FIRMWARE_PATH} ]]; then
        latest_version="embedded OS image"
        firmware_url=${FINAL_FIRMWARE_PATH}
    else
        set -e
        latest=$(curl --silent --show-error --location-trusted ${LATEST_URL})
        latest=$(jq -r '.path,.version,.date' <<<"${latest}")
        latest=(${latest})
        latest_path=${latest[0]}
        latest_version=${latest[1]}
        firmware_url="${BASE_URL}${latest_path}"
        set +e
    fi

    msg_background "${latest_version}"
    touch /var/run/panic_prohibited
    ${PROG} upgrade "${firmware_url}"
}

case "$1" in
    start)
        start
        ;;
    
    stop)
        ;;

    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
