#!/usr/bin/env python

import binascii
import time

import pyatecc


ECC_SLOT = 0
RETRIES = 10


def show_info():
    atecc = pyatecc.ATECC(1)
    ecc_serial_number = atecc.serial_number.lower()

    print(ecc_serial_number)


if __name__ == '__main__':
    for _ in range(RETRIES):
        try:
            show_info()
            break

        except Exception:
            time.sleep(0.5)

    else:
        raise RuntimeError('Timeout when talking to ECC')

