#!/usr/bin/env python

import binascii

import chamutils


def show_info():
    cpu_serial_number = chamutils.get_unit_serial_number()
    ecc_serial_number = chamutils.get_ecc_serial_number()
    pub_key = chamutils.get_ecc_pub_key()
    pub_key_hex = binascii.hexlify(pub_key).decode()

    print(f'{cpu_serial_number} {ecc_serial_number} {pub_key_hex}')


if __name__ == '__main__':
    show_info()
